server:
  port: 9001
spring:
  application:
    name: stock
  cloud:
    nacos:
      server-addr: http://10.6.121.60:8848
      discovery:
        username: nacos
        password: Eimisd@2023
        namespace: public