server:
  port: 9001
spring:
  application:
    name: stock
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        username: nacos
        password: nacos
        namespace: 5f5b4d39-7b75-4b59-a237-046b3611d34a