spring:
  profiles:
    active: "dev"
  application:
    name: stock

---
spring:
  cloud:
    nacos:
      server-addr: http://playgound:8848
      username: nacos
      password: Eimisd@2023
      discovery:
        namespace: public
        ephemeral: false
      config:
        namespace: public
  config:
    activate:
      on-profile: dev
    import:
      - optional:nacos:${spring.application.name}.yaml

---
spring:
  cloud:
    nacos:
      server-addr: http://playgound:8848
      username: nacos
      password: Eimisd@2023
      discovery:
        namespace: public
      config:
        namespace: public
  config:
    activate:
      on-profile: prod
    import:
      - optional:nacos:${spring.application.name}.yaml